/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 c:\ThreeStyle.ai\Model sandbox\flo\editing_table_design.glb 
Author: RAO (https://sketchfab.com/rdcanime)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/editing-table-design-e7632fcf1b434babaed90f49086728e4
Title: Editing Table Design
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/editing_table_design.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.063}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Secondary_workstation_Shiny_Black_0.geometry} material={materials.Shiny_Black} />
          <mesh geometry={nodes.Secondary_workstation_NEON_0.geometry} material={materials.NEON} />
          <mesh geometry={nodes.Mouse_mat_Matte_Black_0.geometry} material={materials.Matte_Black} />
          <mesh geometry={nodes.Carpet_Carpet_Texture_0.geometry} material={materials.Carpet_Texture} />
          <mesh geometry={nodes.Screen_B_Shiny_Black_0.geometry} material={materials.Shiny_Black} />
          <mesh geometry={nodes.Screen_B_Screen_0.geometry} material={materials.Screen} />
          <mesh geometry={nodes.Main_workstation_White_Shiny_0.geometry} material={materials.White_Shiny} />
          <mesh geometry={nodes.Main_workstation_NEON_0.geometry} material={materials.NEON} />
          <mesh geometry={nodes.Screen_A_White_Shiny_0.geometry} material={materials.White_Shiny} />
          <mesh geometry={nodes.Screen_A_Screen_0.geometry} material={materials.Screen} />
          <mesh geometry={nodes.Screen_C_Shiny_Black_0.geometry} material={materials.Shiny_Black} />
          <mesh geometry={nodes.Screen_C_Screen_0.geometry} material={materials.Screen} />
          <mesh geometry={nodes.Main_Table_Wood_0.geometry} material={materials.Wood} />
          <mesh geometry={nodes.Main_Table_Matte_Black_0.geometry} material={materials.Matte_Black} />
          <mesh geometry={nodes.Main_Table_Pegs_Texture_0.geometry} material={materials.Pegs_Texture} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/editing_table_design.glb')
