/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 c:\ThreeStyle.ai\public\models\mic.glb --transform 
Files: c:\ThreeStyle.ai\public\models\mic.glb [3.49MB] > C:\ThreeStyle.ai\src\components\stage\mic-transformed.glb [262.96KB] (92%)
Author: FatWasHere (https://sketchfab.com/fathin880)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/standing-microphone-0fb5da6bfe424f0ab6b447d431db9fab
Title: Standing Microphone
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/optimized/mic-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[-12.531, 22.844, -17.673]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.142} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.PaletteMaterial002} position={[-12.521, 22.595, -17.673]} rotation={[0, Math.PI / 2, 0]} scale={0.019} />
    </group>
  )
}

useGLTF.preload('/models/optimized/mic-transformed.glb')
