/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/editing_table_design.glb -o src/3d/modules/furniture/EditingTable.tsx -r public -t 
Author: RAO (https://sketchfab.com/rdcanime)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/editing-table-design-e7632fcf1b434babaed90f49086728e4
Title: Editing Table Design
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Secondary_workstation_Shiny_Black_0: THREE.Mesh
    Secondary_workstation_NEON_0: THREE.Mesh
    Mouse_mat_Matte_Black_0: THREE.Mesh
    Carpet_Carpet_Texture_0: THREE.Mesh
    Screen_B_Shiny_Black_0: THREE.Mesh
    Screen_B_Screen_0: THREE.Mesh
    Main_workstation_White_Shiny_0: THREE.Mesh
    Main_workstation_NEON_0: THREE.Mesh
    Screen_A_White_Shiny_0: THREE.Mesh
    Screen_A_Screen_0: THREE.Mesh
    Screen_C_Shiny_Black_0: THREE.Mesh
    Screen_C_Screen_0: THREE.Mesh
    Main_Table_Wood_0: THREE.Mesh
    Main_Table_Matte_Black_0: THREE.Mesh
    Main_Table_Pegs_Texture_0: THREE.Mesh
  }
  materials: {
    Shiny_Black: THREE.MeshStandardMaterial
    NEON: THREE.MeshStandardMaterial
    Matte_Black: THREE.MeshStandardMaterial
    Carpet_Texture: THREE.MeshStandardMaterial
    Screen: THREE.MeshStandardMaterial
    White_Shiny: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
    Pegs_Texture: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function EditingTable(props: any) {
  const { nodes, materials } = useGLTF('/models/optimized/editing_table.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.063}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Secondary_workstation_Shiny_Black_0.geometry} material={materials.Shiny_Black} />
          <mesh geometry={nodes.Secondary_workstation_NEON_0.geometry} material={materials.NEON} />
          <mesh geometry={nodes.Mouse_mat_Matte_Black_0.geometry} material={materials.Matte_Black} />
          <mesh geometry={nodes.Carpet_Carpet_Texture_0.geometry} material={materials.Carpet_Texture} />
          {/* <mesh geometry={nodes.Screen_B_Shiny_Black_0.geometry} material={materials.Shiny_Black} />
          <mesh geometry={nodes.Screen_B_Screen_0.geometry} material={materials.Screen} /> */}
          <mesh geometry={nodes.Main_workstation_White_Shiny_0.geometry} material={materials.White_Shiny} />
          <mesh geometry={nodes.Main_workstation_NEON_0.geometry} material={materials.NEON} />
          {/* <mesh geometry={nodes.Screen_A_White_Shiny_0.geometry} material={materials.White_Shiny} />
          <mesh geometry={nodes.Screen_A_Screen_0.geometry} material={materials.Screen} />
          <mesh geometry={nodes.Screen_C_Shiny_Black_0.geometry} material={materials.Shiny_Black} />
          <mesh geometry={nodes.Screen_C_Screen_0.geometry} material={materials.Screen} /> */}
          <mesh geometry={nodes.Main_Table_Wood_0.geometry} material={materials.Wood} />
          <mesh geometry={nodes.Main_Table_Matte_Black_0.geometry} material={materials.Matte_Black} />
          <mesh geometry={nodes.Main_Table_Pegs_Texture_0.geometry} material={materials.Pegs_Texture} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/optimized/editing_table.glb');
